=== HenryGetz/op-cli/cli/schemas/baseline.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://op-cli.local/schemas/baseline.v1.json",
  "title": "caliper baseline response",
  "type": "object",
  "required": [
    "schema_version",
    "command",
    "request_id",
    "timestamp_utc",
    "status",
    "error",
    "warnings",
    "meta",
    "baseline"
  ],
  "properties": {
    "schema_version": {
      "type": "string",
      "const": "1.1"
    },
    "command": {
      "type": "string",
      "const": "baseline"
    },
    "request_id": {
      "type": "string"
    },
    "timestamp_utc": {
      "type": "string",
      "format": "date-time"
    },
    "status": {
      "type": "string",
      "enum": [
        "success",
        "error"
      ]
    },
    "error": {
      "type": [
        "object",
        "null"
      ]
    },
    "warnings": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "meta": {
      "type": "object",
      "required": [
        "command",
        "request_id",
        "timestamp_utc",
        "image_path",
        "image_width",
        "image_height",
        "processing_time_ms",
        "omniparser_version",
        "cli_version"
      ],
      "additionalProperties": true
    },
    "baseline": {
      "type": "object",
      "required": [
        "config_path",
        "project_name",
        "reference_image",
        "viewport",
        "region_count",
        "assertion_count",
        "config"
      ],
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== HenryGetz/op-cli/validation/cli-baseline.json
{"baseline": {"assertion_count": 124, "config": {"assertions": [{"description": "e-0db25b4d6de100e7 width baseline", "expected": 492, "id": "region-e-0db25b4d6de100e7-width", "property": "width", "region": "e-0db25b4d6de100e7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-0db25b4d6de100e7 height baseline", "expected": 32, "id": "region-e-0db25b4d6de100e7-height", "property": "height", "region": "e-0db25b4d6de100e7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-b53e5c16e959539d width baseline", "expected": 85, "id": "region-e-b53e5c16e959539d-width", "property": "width", "region": "e-b53e5c16e959539d", "tolerance": 5, "type": "region_dimension"}, {"description": "e-b53e5c16e959539d height baseline", "expected": 19, "id": "region-e-b53e5c16e959539d-height", "property": "height", "region": "e-b53e5c16e959539d", "tolerance": 5, "type": "region_dimension"}, {"description": "e-0039ae2fb750af49 width baseline", "expected": 72, "id": "region-e-0039ae2fb750af49-width", "property": "width", "region": "e-0039ae2fb750af49", "tolerance": 5, "type": "region_dimension"}, {"description": "e-0039ae2fb750af49 height baseline", "expected": 34, "id": "region-e-0039ae2fb750af49-height", "property": "height", "region": "e-0039ae2fb750af49", "tolerance": 5, "type": "region_dimension"}, {"description": "e-c177e9032cba0d50 width baseline", "expected": 113, "id": "region-e-c177e9032cba0d50-width", "property": "width", "region": "e-c177e9032cba0d50", "tolerance": 5, "type": "region_dimension"}, {"description": "e-c177e9032cba0d50 height baseline", "expected": 19, "id": "region-e-c177e9032cba0d50-height", "property": "height", "region": "e-c177e9032cba0d50", "tolerance": 5, "type": "region_dimension"}, {"description": "e-da9d4afa215608c9 width baseline", "expected": 58, "id": "region-e-da9d4afa215608c9-width", "property": "width", "region": "e-da9d4afa215608c9", "tolerance": 5, "type": "region_dimension"}, {"description": "e-da9d4afa215608c9 height baseline", "expected": 32, "id": "region-e-da9d4afa215608c9-height", "property": "height", "region": "e-da9d4afa215608c9", "tolerance": 5, "type": "region_dimension"}, {"description": "e-87ef3ca480209a1d width baseline", "expected": 81, "id": "region-e-87ef3ca480209a1d-width", "property": "width", "region": "e-87ef3ca480209a1d", "tolerance": 5, "type": "region_dimension"}, {"description": "e-87ef3ca480209a1d height baseline", "expected": 33, "id": "region-e-87ef3ca480209a1d-height", "property": "height", "region": "e-87ef3ca480209a1d", "tolerance": 5, "type": "region_dimension"}, {"description": "e-dbc038a7a1bc5a5c width baseline", "expected": 40, "id": "region-e-dbc038a7a1bc5a5c-width", "property": "width", "region": "e-dbc038a7a1bc5a5c", "tolerance": 5, "type": "region_dimension"}, {"description": "e-dbc038a7a1bc5a5c height baseline", "expected": 18, "id": "region-e-dbc038a7a1bc5a5c-height", "property": "height", "region": "e-dbc038a7a1bc5a5c", "tolerance": 5, "type": "region_dimension"}, {"description": "e-0166f2840d634fc2 width baseline", "expected": 24, "id": "region-e-0166f2840d634fc2-width", "property": "width", "region": "e-0166f2840d634fc2", "tolerance": 5, "type": "region_dimension"}, {"description": "e-0166f2840d634fc2 height baseline", "expected": 17, "id": "region-e-0166f2840d634fc2-height", "property": "height", "region": "e-0166f2840d634fc2", "tolerance": 5, "type": "region_dimension"}, {"description": "e-cb18bf1ea08650d2 width baseline", "expected": 98, "id": "region-e-cb18bf1ea08650d2-width", "property": "width", "region": "e-cb18bf1ea08650d2", "tolerance": 5, "type": "region_dimension"}, {"description": "e-cb18bf1ea08650d2 height baseline", "expected": 23, "id": "region-e-cb18bf1ea08650d2-height", "property": "height", "region": "e-cb18bf1ea08650d2", "tolerance": 5, "type": "region_dimension"}, {"description": "e-5839426cf18dd47f width baseline", "expected": 28, "id": "region-e-5839426cf18dd47f-width", "property": "width", "region": "e-5839426cf18dd47f", "tolerance": 5, "type": "region_dimension"}, {"description": "e-5839426cf18dd47f height baseline", "expected": 16, "id": "region-e-5839426cf18dd47f-height", "property": "height", "region": "e-5839426cf18dd47f", "tolerance": 5, "type": "region_dimension"}, {"description": "e-8c2e6d1f7c9f47b7 width baseline", "expected": 65, "id": "region-e-8c2e6d1f7c9f47b7-width", "property": "width", "region": "e-8c2e6d1f7c9f47b7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-8c2e6d1f7c9f47b7 height baseline", "expected": 42, "id": "region-e-8c2e6d1f7c9f47b7-height", "property": "height", "region": "e-8c2e6d1f7c9f47b7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-d66e3a0ddb16f50b width baseline", "expected": 76, "id": "region-e-d66e3a0ddb16f50b-width", "property": "width", "region": "e-d66e3a0ddb16f50b", "tolerance": 5, "type": "region_dimension"}, {"description": "e-d66e3a0ddb16f50b height baseline", "expected": 46, "id": "region-e-d66e3a0ddb16f50b-height", "property": "height", "region": "e-d66e3a0ddb16f50b", "tolerance": 5, "type": "region_dimension"}, {"description": "e-ad2b980831d94640 width baseline", "expected": 23, "id": "region-e-ad2b980831d94640-width", "property": "width", "region": "e-ad2b980831d94640", "tolerance": 5, "type": "region_dimension"}, {"description": "e-ad2b980831d94640 height baseline", "expected": 16, "id": "region-e-ad2b980831d94640-height", "property": "height", "region": "e-ad2b980831d94640", "tolerance": 5, "type": "region_dimension"}, {"description": "e-32dca882d8bfa19b width baseline", "expected": 161, "id": "region-e-32dca882d8bfa19b-width", "property": "width", "region": "e-32dca882d8bfa19b", "tolerance": 5, "type": "region_dimension"}, {"description": "e-32dca882d8bfa19b height baseline", "expected": 20, "id": "region-e-32dca882d8bfa19b-height", "property": "height", "region": "e-32dca882d8bfa19b", "tolerance": 5, "type": "region_dimension"}, {"description": "e-565936294f90ee7f width baseline", "expected": 154, "id": "region-e-565936294f90ee7f-width", "property": "width", "region": "e-565936294f90ee7f", "tolerance": 5, "type": "region_dimension"}, {"description": "e-565936294f90ee7f height baseline", "expected": 17, "id": "region-e-565936294f90ee7f-height", "property": "height", "region": "e-565936294f90ee7f", "tolerance": 5, "type": "region_dimension"}, {"description": "e-74dbe4b5776e299e width baseline", "expected": 84, "id": "region-e-74dbe4b5776e299e-width", "property": "width", "region": "e-74dbe4b5776e299e", "tolerance": 5, "type": "region_dimension"}, {"description": "e-74dbe4b5776e299e height baseline", "expected": 33, "id": "region-e-74dbe4b5776e299e-height", "property": "height", "region": "e-74dbe4b5776e299e", "tolerance": 5, "type": "region_dimension"}, {"description": "e-f8c89a9ec221de83 width baseline", "expected": 127, "id": "region-e-f8c89a9ec221de83-width", "property": "width", "region": "e-f8c89a9ec221de83", "tolerance": 5, "type": "region_dimension"}, {"description": "e-f8c89a9ec221de83 height baseline", "expected": 17, "id": "region-e-f8c89a9ec221de83-height", "property": "height", "region": "e-f8c89a9ec221de83", "tolerance": 5, "type": "region_dimension"}, {"description": "e-62f470aa9be56a33 width baseline", "expected": 229, "id": "region-e-62f470aa9be56a33-width", "property": "width", "region": "e-62f470aa9be56a33", "tolerance": 5, "type": "region_dimension"}, {"description": "e-62f470aa9be56a33 height baseline", "expected": 57, "id": "region-e-62f470aa9be56a33-height", "property": "height", "region": "e-62f470aa9be56a33", "tolerance": 5, "type": "region_dimension"}, {"description": "e-a246b38fb3dc5c64 width baseline", "expected": 111, "id": "region-e-a246b38fb3dc5c64-width", "property": "width", "region": "e-a246b38fb3dc5c64", "tolerance": 5, "type": "region_dimension"}, {"description": "e-a246b38fb3dc5c64 height baseline", "expected": 49, "id": "region-e-a246b38fb3dc5c64-height", "property": "height", "region": "e-a246b38fb3dc5c64", "tolerance": 5, "type": "region_dimension"}, {"description": "e-3ea1b9bcf88fce43 width baseline", "expected": 108, "id": "region-e-3ea1b9bcf88fce43-width", "property": "width", "region": "e-3ea1b9bcf88fce43", "tolerance": 5, "type": "region_dimension"}, {"description": "e-3ea1b9bcf88fce43 height baseline", "expected": 48, "id": "region-e-3ea1b9bcf88fce43-height", "property": "height", "region": "e-3ea1b9bcf88fce43", "tolerance": 5, "type": "region_dimension"}, {"description": "e-564330b59cbd96a1 width baseline", "expected": 134, "id": "region-e-564330b59cbd96a1-width", "property": "width", "region": "e-564330b59cbd96a1", "tolerance": 5, "type": "region_dimension"}, {"description": "e-564330b59cbd96a1 height baseline", "expected": 30, "id": "region-e-564330b59cbd96a1-height", "property": "height", "region": "e-564330b59cbd96a1", "tolerance": 5, "type": "region_dimension"}, {"description": "e-f66b0fdb308ffae7 width baseline", "expected": 415, "id": "region-e-f66b0fdb308ffae7-width", "property": "width", "region": "e-f66b0fdb308ffae7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-f66b0fdb308ffae7 height baseline", "expected": 299, "id": "region-e-f66b0fdb308ffae7-height", "property": "height", "region": "e-f66b0fdb308ffae7", "tolerance": 5, "type": "region_dimension"}, {"description": "e-3260bba0f74f72e0 width baseline", "expected": 132, "id": "region-e-3260bba0f74f72e0-width", "property": "width", "region": "e-3260bba0f74f72e0", "tolerance": 5, "type": "region_dimension"}, {"description": "e-3260bba0f74f72e0 height baseline", "expected": 28, "id": "region-e-3260bba0f74f72e0-height", "property": "height", "region": "e-3260bba0f74f72e0", "tolerance": 5, "type": "region_dimension"}, {"description": "e-4e94b174cdcf56bc width baseline", "expected": 107, "id": "region-e-4e94b174cdcf56bc-width", "property": "width", "region": "e-4e94b174cdcf56bc", "tolerance": 5, "type": "region_dimension"}, {"description": "e-4e94b174cdcf56bc height baseline", "expected": 33, "id": "r
