=== HenryGetz/op-cli/cli/schemas/diff.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://op-cli.local/schemas/diff.v1.json",
  "title": "caliper diff response",
  "type": "object",
  "required": [
    "schema_version",
    "command",
    "request_id",
    "timestamp_utc",
    "status",
    "error",
    "warnings",
    "meta",
    "diff"
  ],
  "properties": {
    "schema_version": {
      "type": "string",
      "const": "1.1"
    },
    "command": {
      "type": "string",
      "const": "diff"
    },
    "request_id": {
      "type": "string"
    },
    "timestamp_utc": {
      "type": "string",
      "format": "date-time"
    },
    "status": {
      "type": "string",
      "enum": [
        "success",
        "error"
      ]
    },
    "error": {
      "type": [
        "object",
        "null"
      ]
    },
    "warnings": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "meta": {
      "type": "object",
      "required": [
        "command",
        "request_id",
        "timestamp_utc",
        "image_path",
        "image_width",
        "image_height",
        "processing_time_ms",
        "omniparser_version",
        "cli_version"
      ],
      "additionalProperties": true
    },
    "diff": {
      "type": "object",
      "required": [
        "removed_elements",
        "added_elements",
        "moved_or_resized",
        "similarity_score",
        "matched_pairs",
        "unchanged_pairs",
        "save_diff_path"
      ],
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== HenryGetz/op-cli/validation/cli-diff.json
{"command": "diff", "diff": {"added_elements": [{"bbox": {"height": 37, "width": 139, "x": 477, "y": 279}, "bbox_ratio": [0.74563622, 0.69731188, 0.96232319, 0.79045123], "confidence": 0.640575, "element_id": "e_ce19d492f8995748", "element_type": "icon", "index": 11, "interactable": true, "label": "95mL", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 21, "width": 21, "x": 11, "y": 56}, "bbox_ratio": [0.01676006, 0.13883324, 0.04979623, 0.19267571], "confidence": 0.148493, "element_id": "e_0a0aa8e65c7ad3a5", "element_type": "icon", "index": 21, "interactable": true, "label": "A blurry image or profile picture.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 115, "width": 451, "x": 61, "y": 169}, "bbox_ratio": [0.0946105, 0.42230621, 0.80055732, 0.70912534], "confidence": 0.396658, "element_id": "e_5834ba5956cb3dc1", "element_type": "icon", "index": 20, "interactable": true, "label": "A computer screen with a command prompt that is not lit up.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 35, "width": 340, "x": 78, "y": 280}, "bbox_ratio": [0.12125526, 0.70026457, 0.65305316, 0.78853941], "confidence": 0.682015, "element_id": "e_cf2aa9d0542b6382", "element_type": "icon", "index": 19, "interactable": true, "label": "A sticky note pad.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 43, "width": 120, "x": 519, "y": 0}, "bbox_ratio": [0.81077766, 0.00071152, 0.99839574, 0.10632126], "confidence": 0.235719, "element_id": "e_b385d7335e9ad548", "element_type": "icon", "index": 12, "interactable": true, "label": "ACIST Pro", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 16, "width": 72, "x": 67, "y": 12}, "bbox_ratio": [0.10544667, 0.0290266, 0.21792729, 0.06985936], "confidence": 0.227112, "element_id": "e_6a45dabd314ab95a", "element_type": "icon", "index": 13, "interactable": true, "label": "Cardiac", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 16, "width": 48, "x": 244, "y": 56}, "bbox_ratio": [0.38139805, 0.14100517, 0.45587954, 0.17961143], "confidence": 0.112966, "element_id": "e_76b8d1480bb81838", "element_type": "icon", "index": 15, "interactable": true, "label": "Disarm", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 13, "width": 65, "x": 79, "y": 366}, "bbox_ratio": [0.12324009, 0.91583753, 0.22502677, 0.9480617], "confidence": 0.10486, "element_id": "e_e71f0b356e2a3fae", "element_type": "icon", "index": 16, "interactable": true, "label": "Dr.Johnson", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 40, "width": 137, "x": 480, "y": 156}, "bbox_ratio": [0.75007486, 0.39032027, 0.96398151, 0.48997331], "confidence": 0.06402, "element_id": "e_8bb59f0a3d509611", "element_type": "icon", "index": 18, "interactable": true, "label": "Last Injection 9.5mL/s 18.5mL", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 26, "width": 140, "x": 478, "y": 201}, "bbox_ratio": [0.74668515, 0.50247496, 0.9649995, 0.56736845], "confidence": 0.181242, "element_id": "e_47f81376fd9892b0", "element_type": "icon", "index": 14, "interactable": true, "label": "X-ray Sync", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 19, "width": 38, "x": 479, "y": 124}, "bbox_ratio": [0.74843752, 0.31, 0.80781251, 0.35749999], "confidence": 0.916952, "element_id": "e_2d071a727337eba6", "element_type": "text", "index": 7, "interactable": false, "label": "0.5 s", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 56, "width": 118, "x": 97, "y": 133}, "bbox_ratio": [0.1515625, 0.33250001, 0.3359375, 0.4725], "confidence": 0.999074, "element_id": "e_2e543a1a7d97cfcf", "element_type": "text", "index": 5, "interactable": false, "label": "11.0", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 57, "width": 130, "x": 291, "y": 133}, "bbox_ratio": [0.45468751, 0.33250001, 0.65781248, 0.47499999], "confidence": 0.999151, "element_id": "e_2d8dca82c61541e4", "element_type": "text", "index": 6, "interactable": false, "label": "21.0", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 10, "width": 61, "x": 545, "y": 314}, "bbox_ratio": [0.8515625, 0.78500003, 0.94687498, 0.81], "confidence": 0.884791, "element_id": "e_b286d1cae7227ba2", "element_type": "text", "index": 10, "interactable": false, "label": "Ato refill 1 30 ml", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 10, "width": 80, "x": 479, "y": 264}, "bbox_ratio": [0.74843752, 0.66000003, 0.87343752, 0.685], "confidence": 0.981141, "element_id": "e_0042b0f7049628f6", "element_type": "text", "index": 8, "interactable": false, "label": "Contrast Available", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 16, "width": 90, "x": 82, "y": 112}, "bbox_ratio": [0.128125, 0.28, 0.26875001, 0.31999999], "confidence": 0.964924, "element_id": "e_e89dcef848b31ad1", "element_type": "text", "index": 2, "interactable": false, "label": "Flow Rate (mL/s)", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 20, "width": 201, "x": 159, "y": 9}, "bbox_ratio": [0.24843749, 0.0225, 0.5625, 0.0725], "confidence": 0.897783, "element_id": "e_9bb7a6f90d846d2c", "element_type": "text", "index": 0, "interactable": false, "label": "LCA RCA LV/Aorta", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 14, "width": 164, "x": 70, "y": 57}, "bbox_ratio": [0.109375, 0.1425, 0.36562499, 0.17749999], "confidence": 0.990402, "element_id": "e_5cd055395b599f0d", "element_type": "text", "index": 1, "interactable": false, "label": "Ready:Large Injection", "source": "box_ocr_content_ocr"}, {"bbox": {"height": 18, "width": 69, "x": 282, "y": 112}, "bbox_ratio": [0.44062501, 0.28, 0.54843748, 0.32499999], "confidence": 0.998348, "element_id": "e_14259a9a02f29c1b", "element_type": "text", "index": 3, "interactable": false, "label": "Volume (mL)", "source": "box_ocr_content_ocr"}], "matched_pairs": 3, "moved_or_resized": [{"delta": {"height": -22, "width": -49, "x": -552, "y": -305}, "element_type": "icon", "image1_bbox": {"height": 48, "width": 108, "x": 1030, "y": 636}, "image1_index": 19, "image2_bbox": {"height": 26, "width": 59, "x": 478, "y": 331}, "image2_index": 17, "label": "PURGE"}, {"delta": {"height": -18, "width": -53, "x": -201, "y": -292}, "element_type": "text", "image1_bbox": {"height": 33, "width": 84, "x": 449, "y": 608}, "image1_index": 15, "image2_bbox": {"height": 15, "width": 31, "x": 248, "y": 316}, "image2_index": 9, "label": "51%"}, {"delta": {"height": -5, "width": -39, "x": -553, "y": -48}, "element_type": "text", "image1_bbox": {"height": 19, "width": 85, "x": 1031, "y": 159}, "image1_index": 1, "image2_bbox": {"height": 14, "width": 46, "x": 478, "y": 111}, "image2_index": 4, "label": "Rise Time"}], "removed_elements": [{"bbox": {"height": 57, "width": 229, "x": 1028, "y": 537}, "bbox_ratio": [0.80302811, 0.67095995, 0.98188859, 0.74195325], "confidence": 0.90105, "element_id": "e_62f470aa9be56a33", "element_type": "icon", "index": 17, "interactable": true, "label": "95 mL", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 46, "width": 46, "x": 16, "y": 11}, "bbox_ratio": [0.01261083, 0.01383339, 0.04857552, 0.07068535], "confidence": 0.408891, "element_id": "e_67dd5154a60b6035", "element_type": "icon", "index": 30, "interactable": true, "label": "a horizontal bar or horizontal line.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 37, "width": 28, "x": 26, "y": 327}, "bbox_ratio": [0.02005062, 0.40885314, 0.04252806, 0.45541078], "confidence": 0.299797, "element_id": "e_0b319518e6b50f15", "element_type": "icon", "index": 32, "interactable": true, "label": "A horizontal bar or horizontal line.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 66, "width": 55, "x": 12, "y": 162}, "bbox_ratio": [0.00976043, 0.20259796, 0.05261705, 0.28448129], "confidence": 0.096006, "element_id": "e_91ebb9bf12723ab4", "element_type": "icon", "index": 35, "interactable": true, "label": "A simple design or logo.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 32, "width": 32, "x": 25, "y": 101}, "bbox_ratio": [0.01971423, 0.12563752, 0.0444626, 0.16656646], "confidence": 0.100426, "element_id": "e_45257347fddc5d13", "element_type": "icon", "index": 34, "interactable": true, "label": "A simple icon or logo.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 53, "width": 46, "x": 17, "y": 725}, "bbox_ratio": [0.01359847, 0.90667504, 0.04948031, 0.97233772], "confidence": 0.342132, "element_id": "e_f8ab90f3c00edac6", "element_type": "icon", "index": 31, "interactable": true, "label": "A simple motion blur or moving back or forth.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 38, "width": 34, "x": 24, "y": 250}, "bbox_ratio": [0.01874217, 0.31305054, 0.04523318, 0.3604258], "confidence": 0.132022, "element_id": "e_5b02ce6037edb7b9", "element_type": "icon", "index": 33, "interactable": true, "label": "A simple running or running application.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 29, "width": 59, "x": 1197, "y": 369}, "bbox_ratio": [0.93552434, 0.46160966, 0.98136026, 0.49808747], "confidence": 0.872397, "element_id": "e_6dc10bd9a0aa0d83", "element_type": "icon", "index": 29, "interactable": true, "label": "A single oval shape.", "source": "box_yolo_content_yolo"}, {"bbox": {"height": 28, "width": 132, "x": 1126, "y": 18}, "bbox_ratio": [0.87969077, 0.02227108, 0.98262578, 0.05769115], "confidence": 0.312527, "element_id": "e_3260bba0f74f72e0", "element_type": "icon", "index": 22, "interactable": true, "label": "ACIST Pro'", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 68, "width": 129, "x": 77, "y": 0}, "bbox_ratio": [0.06022668, 0.0, 0.16116886, 0.08512123], "confidence": 0.186415, "element_id": "e_7c800068e549dcf7", "element_type": "icon", "index": 25, "interactable": true, "label": "Cardiac v", "source": "box_yolo_content_ocr"}, {"bbox": {"height": 30, "width": 134, "x": 103, "y": 654}, "bbox_ratio": [0.08079731, 0.81759864, 0.18535507, 0.85469264], "confidence": 0.787166, "element_id": "e_564330b59cbd96a1", "element_type": "icon", "index": 20,
